Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = "Velocity-Test-KP"
    aws.region = "us-west-2"
    aws.ami = "ami-9096e2a0"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/perk387/.ssh/velocity_rsa"
  end
end
