#+AUTHOR: Saptarshi Guha
#+EMAIL: sguha@purdue.edu
#+SHOW: all
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:nil
#+STYLE: <link rel="stylesheet" type="text/css" href="a.css" />
#+TITLE: RHIPE - R and Hadoop Integrated Processing Environment 


RHIPE(phonetic spelling: hree-pay' [1]) is a java package that integrates the R environment with [[http://hadoop.apache.org/core/][Hadoop]], the open source implementation
of Google's mapreduce.  Using RHIPE it is possible to code map-reduce algorithms in R e.g
[1] This is greek for /a moment in time/. See here for pronunciation:
[[http://www.searchgodsword.org/lex/grk/view.cgi?number=4493][Greek Lexicon]]
#+BEGIN_SRC R-example
m <- expression({
for(x in map.values){
  y <- strsplit(x," +")[[1]]
  for(w in y) rhcollect(w,T)
}})
r <- expression(pre={
  count <- 0
},
reduce={
  count <- count+sum(unlist(reduce.values))
},
post={
 rhcollect(reduce.key,as.integer(count))
})
z=rhmr(map=m,reduce=r,comb=F,inout=c("text","sequence"),ifolder="/tmp/50mil",ofolder='/tmp/tof')
rhex(z)
#+END_SRC

* Download
*Source*

The source code is present on Git, go here [[http://github.com/saptarshiguha/RHIPE/][http://github.com/saptarshiguha/RHIPE/]]

To check out the current version, install =git=
#+BEGIN_SRC sh
git clone git://github.com/saptarshiguha/RHIPE.git
#+END_SRC

To download version =X= e.g =0.45=
#+BEGIN_SRC sh
git clone git://github.com/saptarshiguha/RHIPE.git
git checkout 0.45
#+END_SRC

The current version is *always* the master. 


*Versions*


Read the documentation for installation. Current is the latest version.

| Version | Download         |
|---------+------------------|
| Current | [[file:./dn/rhipe.tar.gz][rhipe.tar.gz]]     |
|     0.5 | [[file:./dn/Rhipe_0.5.tar.gz][Rhipe\_0.5.tar.gz]] |
|    0.44 | [[./dn/rhipe.0.44.tgz][rhipe.0.44.tgz]]   |



* EC2
Download the scripts from [[./dn/rhipeec2.tar.gz][here]], untar it. This will create a folder called =ec2= which has a =bin= folder in it. Modify =ec2/bin/hadoop-ec2-env.sh.template=

**NOTE** For 32 bit instance types only (m1.small, c1.medium). Hopefully, 64 bit will work soon.
* Documentation
The documentation can be found [[file:./doc/html/index.html][here]]. PDF version can be found [[file:./doc/rhipe.pdf][here]]
* News
** Tue Sep  8 15:35:24 EDT 2009
- Moved to Hadoop 0.20
- Uses protobuf for serialization, fewer R types allowed
- Does not depend on Rserve, single R package to install

** Fri Aug  7 2009, Version 0.45
- Web site revamped. Beginning with the current version, the entire
  manual is in PDF or can be accessed  at the [[./doc/index.html/][documentation]] link.
- Source code is available on Git, go to the download page for instructions.
- Stopped seeding via secure random generator, so the user will have
  to seed it to avoid correlated streams. On RHEL linux
 when running =rhlapply= on 145K+ tasks,  =/dev/random= would block.


