#+AUTHOR: Saptarshi Guha
#+EMAIL: sguha@purdue.edu
#+SHOW: all
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:nil
#+STYLE: <link rel="stylesheet" type="text/css" href="a.css" />
#+TITLE: RHIPE - R and Hadoop Integrated Processing Environment 
#

RHIPE(phonetic spelling: hree-pay' [1]) is a java package that integrates the R environment with [[http://hadoop.apache.org/core/][Hadoop]], the open source implementation
of Google's mapreduce.  Using RHIPE it is possible to code map-reduce algorithms in R e.g
[1] This is greek for /a moment in time/. See here for pronunciation:
[[http://www.searchgodsword.org/lex/grk/view.cgi?number=4493][Greek Lexicon]]
#+BEGIN_SRC R-example
m <- expression({
for(x in map.values){
  y <- strsplit(x," +")[[1]]
  for(w in y) rhcollect(w,T)
}})
r <- expression(pre={
  count <- 0
},
reduce={
  count <- count+sum(unlist(reduce.values))
},
post={
 rhcollect(reduce.key,as.integer(count))
})
z=rhmr(map=m,reduce=r,comb=F,inout=c("text","sequence"),ifolder="/tmp/50mil",ofolder='/tmp/tof')
rhex(z)
#+END_SRC

Or just, load Rhipe and type 
#+BEGIN_SRC R-example
rhwordcount(infolder,outfolder)
#+END_SRC
where =infolder= is the input file(or folder of files) or words and outfolder is
the destination directory.
* Mailing List
Mailing list is hosted on Google Groups. The url is
[[http://groups.google.com/group/rhipe]] . Your first post will be moderated.

* Data types supported

Well, a useful subset, but not all, see [[file:./doc/html/datatypes.html][Data Types]]
* More Information
For more information about what RHIPE is and not, read the FAQ.
Please note, this does not work on Mac OS X Snow Leopard.


* Download
*Source*

The source code is present on Git, go here [[http://github.com/saptarshiguha/RHIPE/][http://github.com/saptarshiguha/RHIPE/]]

To check out the current version, install =git=
#+BEGIN_SRC sh
git clone git://github.com/saptarshiguha/RHIPE.git
#+END_SRC

To download version =X= e.g =0.45=
#+BEGIN_SRC sh
git clone git://github.com/saptarshiguha/RHIPE.git
git checkout 0.45
#+END_SRC

The current version is *always* the master. 


*Versions*


Read the documentation for installation. Current is the latest version.

| Version | Download           |
|---------+--------------------|
|    0.53 | [[file:./dn/Rhipe_0.53.tar.gz][Rhipe\_0.53.tar.gz]] |
|    0.52 | [[file:./dn/Rhipe_0.52.tar.gz][Rhipe\_0.52.tar.gz]] |
|    0.51 | [[file:./dn/Rhipe_0.51.tar.gz][Rhipe\_0.51.tar.gz]] |
|     0.5 | [[file:./dn/Rhipe_0.5.tar.gz][Rhipe\_0.5.tar.gz]]  |
|    0.44 | [[./dn/rhipe.0.44.tgz][rhipe.0.44.tgz]]     |



* EC2
Download the scripts from [[./dn/rhipeec2.tar.gz][here]], untar it. This will create a folder called =ec2= which has a =bin= folder in it. Modify =ec2/bin/hadoop-ec2-env.sh.template=

**NOTE** For 32 bit instance types only (m1.small, c1.medium). Hopefully, 64 bit will work soon.
* Documentation
The documentation can be found [[file:./doc/html/index.html][here]]. PDF version can be found [[file:./doc/rhipe.pdf][here]]
* News
** Sun Dec 13 22:11:53 EST 2009
- Release **Version 0.53**
- Bug fixes:
  - Inserted R\_CStackLimits, since I'm using Protobuf a threaded library, it was
    upsetting R.
  -  Removed Rf\_duplicate
- Data types have been enhanced, now allows scalar vectors with attributes. Experimental.
- A result of which can now write data.frames and read them back in.
- Impose 64MB key,value serialization limit(workaround to come in
  future). Objects bigger than this will be written successfully,but will fail
  to read and will cause the job to fail.

** Thu Dec 10 13:28:19 EST 2009
- =rhcounter= ,available in mapreduce code, is more versatile. Previously, ','
  in the counter names would upset Hadoop. Not anymore, see documentation for =rhmr=
** Wed Dec  2 12:44:23 EST 2009
- Failed when running RHIPE from different UID's. Now writes to
  =/tmp/logger-UID=. Version number is still the same
** Mon Oct 12 11:18:31 EDT 2009
- Removed the dependency on rJava. Getting it to work with Hadoop classpaths
  caused to much grief. The actualy RHIPE program remains unchanged but the
  client handler (R package) is a bit slower(?)
** Sun Sep 27 22:01:33 EDT 2009
- Names are *only* read for VECSXP (list objects), because of a strange bug.

** Tue Sep  8 15:35:24 EDT 2009
- Moved to Hadoop 0.20
- Uses protobuf for serialization, fewer R types allowed
- Does not depend on Rserve, single R package to install

** Fri Aug  7 2009, Version 0.45
- Web site revamped. Beginning with the current version, the entire
  manual is in PDF or can be accessed  at the [[./doc/index.html/][documentation]] link.
- Source code is available on Git, go to the download page for instructions.
- Stopped seeding via secure random generator, so the user will have
  to seed it to avoid correlated streams. On RHEL linux
 when running =rhlapply= on 145K+ tasks,  =/dev/random= would block.
  
 
* Contact
sguha -AT- purdue -DOT- edu
