/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_godhuli_rhipe_RHMRHelper */

#ifndef _Included_org_godhuli_rhipe_RHMRHelper
#define _Included_org_godhuli_rhipe_RHMRHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef org_godhuli_rhipe_RHMRHelper_REXP_MAX_SIZE
#define org_godhuli_rhipe_RHMRHelper_REXP_MAX_SIZE 134217728L
/* Inaccessible static: LOG */
/* Inaccessible static: PARTITION_TYPE */
/* Inaccessible static: PARTITION_START */
/* Inaccessible static: PARTITION_END */
/* Inaccessible static: _single_instance */
/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    embedR
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_org_godhuli_rhipe_RHMRHelper_embedR
(JNIEnv *, jobject, jstring, jobjectArray,jint);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    evalR
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_godhuli_rhipe_RHMRHelper_evalR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    exitR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_godhuli_rhipe_RHMRHelper_exitR
  (JNIEnv *, jobject);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    createOpts
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_org_godhuli_rhipe_RHMRHelper_createOpts
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    create_backing_store
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_godhuli_rhipe_RHMRHelper_create_1backing_1store
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    deserialize_kv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_godhuli_rhipe_RHMRHelper_deserialize_1kv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    rewind_kv_stage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_godhuli_rhipe_RHMRHelper_rewind_1kv_1stage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    get_num_to_flush_from_c
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_godhuli_rhipe_RHMRHelper_get_1num_1to_1flush_1from_1c
  (JNIEnv *, jobject);

/*
 * Class:     org_godhuli_rhipe_RHMRHelper
 * Method:    remove_r2j_wrappers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_godhuli_rhipe_RHMRHelper_remove_1r2j_1wrappers
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
